../rtl/uart_16550.sv
../rtl/uart_register_file.sv
../rtl/uart_rx.sv
../rtl/uart_rx_fifo.sv
../rtl/uart_tx.sv
../rtl/uart_tx_fifo.sv
+incdir+../tb
../tb/apb_if.sv
../tb/uart_if.sv
../tb/apb_pkg.sv
../tb/rgm_pkg.sv 
../tb/uart_pkg.sv
../tb/modem_pkg.sv
../tb/apb_uart_pkg.sv
../tb/test.sv
../tb/uart_tb.sv